### ISSUE TITLE
Suggestion: Add options to enable certain filters

### ISSUE THREAD

**Issue by guidomedina** [Xentrk/Stubby-Installer-Asuswrt-Merlin#6]
It would be nice to have the option to enable certain filters, for example in my case following the instructions from https://cleanbrowsing.org/articles/configuring-stubby-dnsovertls I was able to enable the adult filter:
```
tls_ca_file: "/rom/etc/ssl/certs/ca-certificates.crt"
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 2000
tls_connection_retries: 5
tls_backoff_time: 900
timeout: 2000
appdata_dir: "/opt/var/cache/stubby"
listen_addresses:
  - 127.0.0.1@5453
  - 0::1@5453

# Clean browsing free adult filter:
upstream_recursive_servers:
  - address_data: 185.228.168.10
    tls_auth_name: "adult-filter-dns.cleanbrowsing.org"
    tls_pubkey_pinset:
      digest: "sha256"
      value: rb2O6hMTZZ/go/vOqyVLY2lATD9DkD6+BkKfJwYYMFw=
```
